name: Build and Push apisix-dev multi-arch to Docker Hub

on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches: [master]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  build-arm64:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    env:
      APISIX_VERSION: master
      APISIX_DOCKER_TAG: master-debian-dev
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ARM64 image
        run: |
          make push-multiarch-dev-on-debian PLATFORM=linux/arm64
          docker pull apache/apisix:dev-arm64

  build-amd64:
    runs-on: ubuntu-latest
    env:
      APISIX_VERSION: master
      APISIX_DOCKER_TAG: master-debian-dev
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push AMD64 image
        run: |
          make push-multiarch-dev-on-debian PLATFORM=linux/amd64
          docker pull apache/apisix:dev-amd64

  create-manifest:
    runs-on: ubuntu-latest
    needs: [build-arm64, build-amd64]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create multi-arch manifest
        run: |
          docker buildx imagetools create --tag apache/apisix:dev \
            apache/apisix:dev-arm64 \
            apache/apisix:dev-amd64
